version: "3.8"

services:
  api:
    build: ./full-stack-web
    ports:
      - "8080:8080"
    depends_on:
      - oracle-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521/XEPDB1
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apppassword
