version: "3.8"

services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: MYSECRETPASSWORD123
      APP_USER: MYSECRETPASSWORD123
      APP_USER_PASSWORD: MYSECRETPASSWORD123
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./initdb:/container-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  oracle-data: