CREATE TABLE USUARIOS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(200) NOT NULL,
    AVATAR_URL TEXT
);

CREATE TABLE TAREAS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NUMERO INTEGER NOT NULL UNIQUE,
    TITULO VARCHAR(250) NOT NULL,
    IMAGEN_URL TEXT,
    FECHA_LIMITE TIMESTAMPTZ,
    ESTADO VARCHAR(50) NOT NULL,
    PRIORIDAD VARCHAR(50) NOT NULL,
    CATEGORIA VARCHAR(50),
    DESCRIPCION TEXT,
    FECHA_CREACION TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PORCENTAJE_REALIZADO SMALLINT NOT NULL DEFAULT 0,
    TIEMPO_ESTIMADO NUMERIC(7,2),
    AUTOR_ID BIGINT NOT NULL,

    CONSTRAINT FK_TAREAS_AUTOR FOREIGN KEY (AUTOR_ID) REFERENCES USUARIOS (ID),
    CONSTRAINT CHK_PORCENTAJE_REALIZADO CHECK (PORCENTAJE_REALIZADO BETWEEN 0 AND 100),
    CONSTRAINT CHK_TIEMPO_ESTIMADO CHECK (TIEMPO_ESTIMADO >= 0),
    CONSTRAINT CHK_ESTADO_TAREA CHECK (ESTADO IN ('PENDIENTE', 'EN_PROGRESO', 'EN_PRUEBAS', 'HECHO')),
    CONSTRAINT CHK_PRIORIDAD_TAREA CHECK (PRIORIDAD IN ('BAJA', 'MEDIA', 'ALTA', 'URGENTE')),
    CONSTRAINT CHK_CATEGORIA_TAREA CHECK (CATEGORIA IN (
                'ANALISIS',
                'DISENYO',
                'DESARROLLO',
                'MEJORAS',
                'DOCUMENTACION',
                'GESTION',
                'PRUEBAS',
                'SOPORTE'
            )
        )
);

CREATE INDEX IDX_TAREAS_AUTOR_ID ON TAREAS (AUTOR_ID);
CREATE INDEX IDX_TAREAS_ESTADO ON TAREAS (ESTADO);
CREATE INDEX IDX_TAREAS_PRIORIDAD ON TAREAS (PRIORIDAD);
CREATE INDEX IDX_TAREAS_CATEGORIA ON TAREAS (CATEGORIA);
CREATE INDEX IDX_TAREAS_FECHA_LIMITE ON TAREAS (FECHA_LIMITE);

CREATE TABLE TAREAS_ASIGNADOS (
    TAREA_ID BIGINT NOT NULL,
    USUARIO_ID BIGINT NOT NULL,

    PRIMARY KEY (TAREA_ID, USUARIO_ID),

    CONSTRAINT FK_TAREAS_ASIGNADOS_TAREA FOREIGN KEY (TAREA_ID) REFERENCES TAREAS (ID) ON DELETE CASCADE,
    CONSTRAINT FK_TAREAS_ASIGNADOS_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS (ID) ON DELETE CASCADE
);

CREATE INDEX IDX_TAREAS_ASIGNADOS_USUARIO ON TAREAS_ASIGNADOS (USUARIO_ID);

CREATE TABLE COMENTARIOS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TAREA_ID BIGINT NOT NULL,
    AUTOR_ID BIGINT NOT NULL,
    MENSAJE TEXT NOT NULL,
    FECHA TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT FK_COMENTARIOS_TAREA FOREIGN KEY (TAREA_ID) REFERENCES TAREAS (ID) ON DELETE CASCADE,
    CONSTRAINT FK_COMENTARIOS_AUTOR FOREIGN KEY (AUTOR_ID) REFERENCES USUARIOS (ID)
);

CREATE INDEX IDX_COMENTARIOS_TAREA_ID ON COMENTARIOS (TAREA_ID);
CREATE INDEX IDX_COMENTARIOS_AUTOR_ID ON COMENTARIOS (AUTOR_ID);
CREATE INDEX IDX_COMENTARIOS_FECHA ON COMENTARIOS (FECHA);
